version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Collect Static Files
          command: |
            source venv/bin/activate
            python manage.py collectstatic --noinput
      - run:
          name: Run Tests
          command: |
            source venv/bin/activate
            pytest
workflows:
  build-and-test:
    jobs:
      - build